In [6]:
import pandas as pd
import numpy as np

##

### Creating Dataframe using Dictionary

In [8]:
dict1 = {"name" : ["Yogov", "Dhoni", "Tata", "Steve"],
         "Age" : [32, 40, 60, 65],
         "Profession" : ["AIEngineer", "Cricket", "Entrepeneur", "Founder"]
         }

df1 = pd.DataFrame(dict1)
df1

    name  Age   Profession
0  Yogov   32   AIEngineer
1  Dhoni   40      Cricket
2   Tata   60  Entrepeneur
3  Steve   65      Founder

### Creating Dataframe using List and Tuples

In [9]:
tuple1= [("Yogov", 33, "AIEngineer"), ("Dhoni", 40, "Cricket"), ("Tata", "60", "Entrepeneur"), ("Steve", 65, "Founder")]

df2 = pd.DataFrame(tuple1, columns=["Name", "Age", "Profession"])

df2

    Name Age   Profession
0  Yogov  33   AIEngineer
1  Dhoni  40      Cricket
2   Tata  60  Entrepeneur
3  Steve  65      Founder

### Creating Dataframe using List and Dictionary

In [10]:
list_dict1= [
        {"Name" : "Yogov", "Age" : 33, "Profession" : "AIEngineer"}, 
        {"Name" : "Dhoni", "Age" : 40, "Profession" : "Cricket"}, 
        {"Name" : "Tata",  "Age" : 60, "Profession" : "Entrepeneur"}, 
        {"Name" : "Steve", "Age" : 65, "Profession" : "Founder"}
         ]

df3 = pd.DataFrame(list_dict1)
df3

    Name  Age   Profession
0  Yogov   33   AIEngineer
1  Dhoni   40      Cricket
2   Tata   60  Entrepeneur
3  Steve   65      Founder