In [1]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("stock_data.csv", skiprows=1, na_values={
    "eps" : ["not avaialble", "n.a."],
    "revenue" : ["not avaialble", "n.a.", -1],
    "price" : ["not avaialble", "n.a.", -1],
    "people" :  ["not avaialble", "n.a.", -1]
})
df

  tickers            eps  revenue   price         people
0   GOOGL          27.82     87.0   845.0     larry page
1     WMT           4.61    484.0    65.0            NaN
2    MSFT             -1     85.0    64.0     bill gates
3    RIL   not available     50.0  1023.0  mukesh ambani
4    TATA            5.6      NaN     NaN     ratan tata

In [15]:
cols = df.columns
cols

Index(['tickers', 'eps', 'revenue', 'price', 'people'], dtype='object')

In [19]:
df1 =  df.iloc[:,0:2]
df1

  tickers            eps
0   GOOGL          27.82
1     WMT           4.61
2    MSFT             -1
3    RIL   not available
4    TATA            5.6

In [24]:
df2 = df[['tickers', 'price']]
df2 = df2.fillna(0)
df2

  tickers   price
0   GOOGL   845.0
1     WMT    65.0
2    MSFT    64.0
3    RIL   1023.0
4    TATA     0.0

In [25]:
df2.to_csv('new2.csv', columns=["tickers", "price"], index=False)