In [1]:
import pandas as pd
import numpy as np

In [2]:
india_weather = pd.DataFrame({
    "city" : ["mumbai", "delhi", "bengaluru"],
    "temperature" : [32, 45, 30],
    "humidity" : [80, 60, 78]
})

india_weather

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bengaluru           30        78

In [3]:
us_weather = pd.DataFrame({
    "city" : ["new york", "chicago", "orlando"],
    "temperature" : [21, 14, 35],
    "humidity" : [68, 65, 75]
})

us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [4]:
new_df = pd.concat([india_weather, us_weather])
new_df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bengaluru           30        78
0   new york           21        68
1    chicago           14        65
2    orlando           35        75

### Ignoring Index

In [5]:
new_df = pd.concat([india_weather, us_weather], ignore_index=True)
new_df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bengaluru           30        78
3   new york           21        68
4    chicago           14        65
5    orlando           35        75

### Concatenating to dataframe to columns level instead of row level

In [7]:
new_df = pd.concat([india_weather, us_weather], axis=1)
new_df

        city  temperature  humidity      city  temperature  humidity
0     mumbai           32        80  new york           21        68
1      delhi           45        60   chicago           14        65
2  bengaluru           30        78   orlando           35        75

### using index in concat dataframe

In [8]:
new_df = pd.concat([india_weather, us_weather], keys= ["india", "us"])
new_df

              city  temperature  humidity
india 0     mumbai           32        80
      1      delhi           45        60
      2  bengaluru           30        78
us    0   new york           21        68
      1    chicago           14        65
      2    orlando           35        75

In [10]:
new_df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [11]:
new_df = pd.concat([india_weather, us_weather], axis=1, keys=["india", "us"])
new_df

       india                             us
        city temperature humidity      city temperature humidity
0     mumbai          32       80  new york          21       68
1      delhi          45       60   chicago          14       65
2  bengaluru          30       78   orlando          35       75

In [17]:
new_df["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

### Concatenation Using Index

In [19]:
temperature_df = pd.DataFrame({
    "city": ["delhi","mumbai","chennai"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

      city  temperature
0    delhi           32
1   mumbai           45
2  chennai           30

In [20]:
windspeed_df = pd.DataFrame({
    "city": ["delhi","chennai"],
    "windspeed": [7,12],
}, index=[0,2])
windspeed_df

      city  windspeed
0    delhi          7
2  chennai         12

In [22]:
new_df = pd.concat([temperature_df, windspeed_df], axis=1)
new_df

      city  temperature     city  windspeed
0    delhi           32    delhi        7.0
1   mumbai           45      NaN        NaN
2  chennai           30  chennai       12.0

### Concatenate dataframe with series

In [23]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [24]:
new_df = pd.concat([temperature_df, s], axis = 1)
new_df

      city  temperature  event
0    delhi           32  Humid
1   mumbai           45    Dry
2  chennai           30   Rain