In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("weather_by_cities.csv", parse_dates=["day"])
df

          day      city  temperature  windspeed   event
0  2017-01-01  new york           32          6    Rain
1  2017-01-02  new york           36          7   Sunny
2  2017-01-03  new york           28         12    Snow
3  2017-01-04  new york           33          7   Sunny
4  2017-01-01    mumbai           90          5   Sunny
5  2017-01-02    mumbai           85         12     Fog
6  2017-01-03    mumbai           87         15     Fog
7  2017-01-04    mumbai           92          5    Rain
8  2017-01-01     paris           45         20   Sunny
9  2017-01-02     paris           50         13  Cloudy
10 2017-01-03     paris           54          8  Cloudy
11 2017-01-04     paris           42         10  Cloudy

In [11]:
new_df = df.fillna({
    "temperature" : 0,
    "windspeed" : 0,
    "event" : "no event"
})
new_df

          day      city  temperature  windspeed   event
0  2017-01-01  new york           32          6    Rain
1  2017-01-02  new york           36          7   Sunny
2  2017-01-03  new york           28         12    Snow
3  2017-01-04  new york           33          7   Sunny
4  2017-01-01    mumbai           90          5   Sunny
5  2017-01-02    mumbai           85         12     Fog
6  2017-01-03    mumbai           87         15     Fog
7  2017-01-04    mumbai           92          5    Rain
8  2017-01-01     paris           45         20   Sunny
9  2017-01-02     paris           50         13  Cloudy
10 2017-01-03     paris           54          8  Cloudy
11 2017-01-04     paris           42         10  Cloudy

In [13]:
df.pivot(index = "day", columns="city", values = ["temperature", "windspeed"])

           temperature                windspeed
city            mumbai new york paris    mumbai new york paris
day
2017-01-01          90       32    45         5        6    20
2017-01-02          85       36    50        12        7    13
2017-01-03          87       28    54        15       12     8
2017-01-04          92       33    42         5        7    10

### Pivot Table

In [14]:
df = pd.read_csv("weather2.csv")
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [17]:
pivot_tbl_df = df.pivot_table(index = 'date', columns='city', values=["temperature", "humidity"])
pivot_tbl_df

         humidity          temperature
city       mumbai new york      mumbai new york
date
5/1/2017     81.5     55.0        76.5     63.0
5/2/2017     55.5     61.0        81.0     71.0

In [30]:
pivot_tbl_df = df.pivot_table(index = 'date', columns='city', values=["temperature", "humidity"], margins=True)
pivot_tbl_df

         humidity                 temperature
city       mumbai new york    All      mumbai new york     All
date
5/1/2017     81.5     55.0  68.25       76.50     63.0  69.750
5/2/2017     55.5     61.0  58.25       81.00     71.0  76.000
All          68.5     58.0  63.25       78.75     67.0  72.875

In [29]:
pivot_tbl_df = df.pivot_table(index = 'date', columns='city', values=["temperature"], aggfunc="count")
pivot_tbl_df

         temperature
city          mumbai new york
date
5/1/2017           2        2
5/2/2017           2        2

### Grouper

In [32]:
df = pd.read_csv("weather3.csv", parse_dates=['date'])
df

        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

In [33]:
new_df = df.pivot_table(index = pd.Grouper(freq='M', key='date'), columns='city')
new_df

/tmp/ipykernel_30564/651239638.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  new_df = df.pivot_table(index = pd.Grouper(freq='M', key='date'), columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667