In [1]:
import pandas as pd
import numpy as np
import multiprocessing as mp
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("nyc_weather.csv")
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [3]:
row_count = df.shape[0]

In [4]:
df = pd.Series([row_count], name='Row Count')

In [5]:
df.head()

0    31
Name: Row Count, dtype: int64

In [45]:
chunksize = 2
for i in pd.read_csv('nyc_weather.csv', chunksize=16):
    num_chunks = mp.cpu_count()
    print(num_chunks)
    print(type(i))
    data_lst = np.array_split(i, 4)
    print(type(data_lst))
    print(data_lst)
    print(".....................")
    print(data_lst.shape[0])

16
<class 'pandas.core.frame.DataFrame'>
<class 'list'>
[        EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0  1/1/2016           38        23        52                 30.03
1  1/2/2016           36        18        46                 30.02
2  1/3/2016           40        21        47                 29.86
3  1/4/2016           25         9        44                 30.05

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5    NaN
1               10           7.0               0           3    NaN
2               10           8.0               0           1    NaN
3               10           9.0               0           3    NaN

   WindDirDegrees
0             281
1             275
2             277
3             345  ,         EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
4  1/5/2016           20        -3        41                 30.57
5  1/6/2016           33         4        35                 30.50
6  1/7/2016           39        11        33                 30.28
7  1/8/2016           39        29        64                 30.20

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
4               10           5.0               0           0    NaN
5               10           4.0               0           0    NaN
6               10           2.0               0           3    NaN
7               10           4.0               0           8    NaN

   WindDirDegrees
4             333
5             259
6             293
7              79  ,           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
8                 9           8.0               T           8   Rain
9                 4           NaN             1.8           7   Rain
10               10           NaN               0           1    NaN
11               10           6.0               T           4    NaN

    WindDirDegrees
8               76
9              109
10             289
11             235  ,           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
12               10          10.0               0           0    NaN
13               10           5.0               T           7    NaN
14                9           5.0               T           2    NaN
15                8           7.0            0.24           7   Rain

    WindDirDegrees
12             284
13             266
14             101
15             340  ]
.....................

/home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

AttributeError: 'list' object has no attribute 'shape'

In [20]:


partitions = mp.cpu_count()
print(partitions)

data_chunks = np.array_split(df, partitions)

16

/home/yogesh/anaconda3/envs/Pytorch_12_1/lib/python3.11/site-packages/numpy/core/fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [33]:
data_chunks

[        EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 0  1/1/2016           38        23        52                 30.03
 1  1/2/2016           36        18        46                 30.02

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 0               10           8.0               0           5    NaN
 1               10           7.0               0           3    NaN

    WindDirDegrees
 0             281
 1             275  ,
         EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 2  1/3/2016           40        21        47                 29.86
 3  1/4/2016           25         9        44                 30.05

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 2               10           8.0               0           1    NaN
 3               10           9.0               0           3    NaN

    WindDirDegrees
 2             277
 3             345  ,
         EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 4  1/5/2016           20        -3        41                 30.57
 5  1/6/2016           33         4        35                 30.50

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 4               10           5.0               0           0    NaN
 5               10           4.0               0           0    NaN

    WindDirDegrees
 4             333
 5             259  ,
         EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 6  1/7/2016           39        11        33                 30.28
 7  1/8/2016           39        29        64                 30.20

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 6               10           2.0               0           3    NaN
 7               10           4.0               0           8    NaN

    WindDirDegrees
 6             293
 7              79  ,
          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 8   1/9/2016           44        38        77                 30.16
 9  1/10/2016           50        46        71                 29.59

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 8                9           8.0               T           8   Rain
 9                4           NaN             1.8           7   Rain

    WindDirDegrees
 8              76
 9             109  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 10  1/11/2016           33         8        37                 29.92
 11  1/12/2016           35        15        53                 29.85

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 10               10           NaN               0           1    NaN
 11               10           6.0               T           4    NaN

     WindDirDegrees
 10             289
 11             235  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 12  1/13/2016           26         4        42                 29.94
 13  1/14/2016           30        12        47                 29.95

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 12               10          10.0               0           0    NaN
 13               10           5.0               T           7    NaN

     WindDirDegrees
 12             284
 13             266  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 14  1/15/2016           43        31        62                 29.82
 15  1/16/2016           47        37        70                 29.52

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 14                9           5.0               T           2    NaN
 15                8           7.0            0.24           7   Rain

     WindDirDegrees
 14             101
 15             340  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 16  1/17/2016           36        23        66                 29.78
 17  1/18/2016           25         6        53                 29.83

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
 16                8           6.0            0.05           6  Fog-Snow
 17                9          12.0               T           2      Snow

     WindDirDegrees
 16             345
 17             293  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 18  1/19/2016           22         3        42                 30.03
 19  1/20/2016           32        15        49                 30.13

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 18               10          11.0               0           1    NaN
 19               10           6.0               0           2    NaN

     WindDirDegrees
 18             293
 19             302  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 20  1/21/2016           31        11        45                 30.15
 21  1/22/2016           26         6        41                 30.21

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 20               10           6.0               0           1    NaN
 21                9           NaN            0.01           3   Snow

     WindDirDegrees
 20             312
 21              34  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 22  1/23/2016           26        21        78                 29.77
 23  1/24/2016           28        11        53                 29.92

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
 22                1          16.0            2.31           8  Fog-Snow
 23                8           6.0               T           3      Snow

     WindDirDegrees
 22              42
 23             327  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 24  1/25/2016           34        18        54                 30.25
 25  1/26/2016           43        29        56                 30.03

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 24               10           3.0               0           2    NaN
 25               10           7.0               0           2    NaN

     WindDirDegrees
 24             286
 25             244  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 26  1/27/2016           41        22        45                 30.03
 27  1/28/2016           37        20        51                 29.90

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 26               10           7.0               T           3   Rain
 27               10           5.0               0           1    NaN

     WindDirDegrees
 26             311
 27             234  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 28  1/29/2016           36        21        50                 29.58
 29  1/30/2016           34        16        46                 30.01

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 28               10           8.0               0           4    NaN
 29               10           7.0               0           0    NaN

     WindDirDegrees
 28             298
 29             257  ,
           EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
 30  1/31/2016           46        28        52                  29.9

     VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
 30               10           5.0               0           0    NaN

     WindDirDegrees
 30             241  ]

In [34]:
type(data_chunks)

list

In [36]:
data_chunks.shape[0]

AttributeError: 'list' object has no attribute 'shape'

In [3]:
import pandas as pd

In [1]:
world = [["Afghanistan", "Asia", 652230, 25500100, 20343000000],
         ["Albania", "Europe", 28748, 2831741, 12960000000],
         ["Algeria", "Africa", 2381741, 37100000, 188681000000],
         ["Andorra", "Europe", 468, 78115, 3712000000],
         ["Angola", "Africa", 1246700, 20609294, 100990000000]]   

world

[['Afghanistan', 'Asia', 652230, 25500100, 20343000000],
 ['Albania', 'Europe', 28748, 2831741, 12960000000],
 ['Algeria', 'Africa', 2381741, 37100000, 188681000000],
 ['Andorra', 'Europe', 468, 78115, 3712000000],
 ['Angola', 'Africa', 1246700, 20609294, 100990000000]]

In [4]:
df = pd.DataFrame(world, columns = ["name", "continent", "area", "population", "gdp"])
df

          name continent     area  population           gdp
0  Afghanistan      Asia   652230    25500100   20343000000
1      Albania    Europe    28748     2831741   12960000000
2      Algeria    Africa  2381741    37100000  188681000000
3      Andorra    Europe      468       78115    3712000000
4       Angola    Africa  1246700    20609294  100990000000

In [9]:
df1 = df[(df["area"] > 3000000) | (df['population'] > 25000000)]
df1

          name continent     area  population           gdp
0  Afghanistan      Asia   652230    25500100   20343000000
2      Algeria    Africa  2381741    37100000  188681000000